background {
	monitor =
	path = /home/zheri/Pictures/wallpapers/island-night-moon-blurred.png
	color = rgba(37, 150, 190, 0.0)
}

# User label
label {
    monitor = HDMI-A-2
    text = Hello there, $USER.
    text_align = center
    color = rgba(255, 255, 255, 0.85)
    font_size = 14
    font_family = Josefin Sans

	shadow_passes = 1
	shadow_size = 5
	shadow_boost = 0.65

	position = 0, -284
	halign = center
}

# Password input
input-field {
	monitor = HDMI-A-2
	size = 15%, 3.5%
	outline_thickness = 2
	inner_color = rgba(255, 255, 255, 0.2) # no fill

	outer_color = rgba(0c2236ee) rgba(328de0ee) 45deg
	check_color = rgba(1ccf6cee) rgba(1fa29cee) 120deg
	fail_color = rgba(d64242ee) rgba(9d1f5fee) 40deg

	font_color = rgb(255, 255, 255)
	fade_on_empty = false
	rounding = 15

	shadow_passes = 1
	shadow_size = 4
	shadow_boost = 0.55

	position = 0, -320
	halign = center
	valign = center
}

# Date
label {
	monitor = HDMI-A-2
	text = cmd[update:1000] echo "<span font_weight='350'>$(date '+%A, %d %b')</span>"
	text_align = center
	color = rgba(255, 255, 255, 1.0)
	font_size = 24
	font_family = Lato

	shadow_passes = 1
	shadow_size = 5
	shadow_boost = 0.65

	position = 0, 216
	halign = center
	valign = center
}

# Time
label {
	monitor = HDMI-A-2
	text = cmd[update:1000] echo "<span font_weight='600'>$(date '+%I:%M %p')</span>"
	text_align = center
	color = rgba(255, 255, 255, 1.0)
	font_size = 64
	font_family = Josefin Sans

	shadow_passes = 1
	shadow_size = 5
	shadow_boost = 0.65

	position = 0, 144
	halign = center
}
