set-option -sa terminal-overrides ",xterm*:Tc"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

# Bindings
bind -n M-H previous-window
bind -n M-L next-window

# Change prefix default to Ctrl + Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
